apiVersion: v1
kind: Service
metadata:
  labels:
    run: rails-hello
  name: rails-hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: rails-hello
  type: ClusterIP
status:
  loadBalancer: {}
